server:
  port: 6080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    jdbcUrl: jdbc:mysql://192.168.2.120:3306/demo?useUnicode=true&characterEncoding=UTF-8
    user: root
    password: fanzhuankeji
    driverClass: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    acquireIncrement: 11
    acquireRetryAttempts: 7
    maxIdle: 5
    maxActive: 20
    defaultAutoCommit: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.demo.clockin.domain


#系统环境全局变量配置
system:
  base: http://192.168.2.253:6080
  charset: UTF-8
  compName: XXXX有限公司
  name: 后台管理系统
  fileUploadRootPath: D:/lee_work/puxinwork/pringboot/clockin/target/clockin
  fileUploadRootUrl: http://192.168.2.253:6080/clockin/
  fileImageMaxSize: 5
  fileImageUploadPath: images
  fileImageTypes: jpg,png,jpeg,bmp
  defaultManagetLogo: images/default.png





